# Generated by Django 4.2.6 on 2023-12-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mh_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs'),
        ),
    ]
